service: cordless-phone

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2

  environment:
    account_sid: ${ssm:/cordless-phone/account-sid~true}
    auth_token: ${ssm:/cordless-phone/auth-token~true}
    from_number: ${ssm:/cordless-phone/from_number}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  token:
    handler: handler.token
    events:
      - http:
          path: /token
          method: get
  dial:
    handler: handler.dial
    events:
      - http:
          path: /commands/dial
          method: post
  hangup:
    handler: handler.hangup
    events:
      - http:
          path: /commands/hangup
          method: post